/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoFeatureFlagsRouteImport } from './routes/demo/feature-flags'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFeatureFlagsRoute = DemoFeatureFlagsRouteImport.update({
  id: '/demo/feature-flags',
  path: '/demo/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/feature-flags': typeof DemoFeatureFlagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/feature-flags': typeof DemoFeatureFlagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/feature-flags': typeof DemoFeatureFlagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/feature-flags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/feature-flags'
  id: '__root__' | '/' | '/demo/feature-flags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoFeatureFlagsRoute: typeof DemoFeatureFlagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/feature-flags': {
      id: '/demo/feature-flags'
      path: '/demo/feature-flags'
      fullPath: '/demo/feature-flags'
      preLoaderRoute: typeof DemoFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoFeatureFlagsRoute: DemoFeatureFlagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
