/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoProtectedRouteImport } from './routes/demo/protected'
import { Route as DemoFeatureFlagsRouteImport } from './routes/demo/feature-flags'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoProtectedRoute = DemoProtectedRouteImport.update({
  id: '/demo/protected',
  path: '/demo/protected',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFeatureFlagsRoute = DemoFeatureFlagsRouteImport.update({
  id: '/demo/feature-flags',
  path: '/demo/feature-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/feature-flags': typeof DemoFeatureFlagsRoute
  '/demo/protected': typeof DemoProtectedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/feature-flags': typeof DemoFeatureFlagsRoute
  '/demo/protected': typeof DemoProtectedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/demo/feature-flags': typeof DemoFeatureFlagsRoute
  '/demo/protected': typeof DemoProtectedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/callback' | '/demo/feature-flags' | '/demo/protected'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/callback' | '/demo/feature-flags' | '/demo/protected'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/demo/feature-flags'
    | '/demo/protected'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DemoFeatureFlagsRoute: typeof DemoFeatureFlagsRoute
  DemoProtectedRoute: typeof DemoProtectedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/protected': {
      id: '/demo/protected'
      path: '/demo/protected'
      fullPath: '/demo/protected'
      preLoaderRoute: typeof DemoProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/feature-flags': {
      id: '/demo/feature-flags'
      path: '/demo/feature-flags'
      fullPath: '/demo/feature-flags'
      preLoaderRoute: typeof DemoFeatureFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DemoFeatureFlagsRoute: DemoFeatureFlagsRoute,
  DemoProtectedRoute: DemoProtectedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
